[tls.options]

  [tls.options.default]
    minVersion = "VersionTLS12"

    cipherSuites = [
        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
        "TLS_AES_128_GCM_SHA256",
        "TLS_AES_256_GCM_SHA384",
        "TLS_CHACHA20_POLY1305_SHA256"
    ]

    sniStrict = true

  [tls.options.myTLSOptions]
    [tls.options.myTLSOptions.clientAuth]
		caFiles = ["client.crt"]
		clientAuthType = "RequireAndVerifyClientCert"

[http]
